const UserActionTypes = {
    SET_CURRENT_USER : 'SET_CURRENT_USER',
    GOOGLE_SIGN_IN_START: 'GOOGLE_SIGN_IN_START',
    GOOGLE_SIGN_IN_SUCESS: 'GOOGLE_SIGN_IN_SUCESS',
    GOOGLE_SIGN_IN_FALIURE: 'GOOGLE_SIGN_IN_FALIURE',
    EMAIL_SIGN_IN_START: 'EMAIL_SIGN_IN_START',
    EMAIL_SIGN_IN_SUCESS: 'EMAIL_SIGN_IN_SUCESS',
    EMAIL_SIGN_IN_FALIURE: 'EMAIL_SIGN_IN_FALIURE',
    CHECK_USER_SESSION: 'CHECK_USER_SESSION',
    SIGN_OUT_START : 'SIGN_OUT_START',
    SIGN_OUT_SUCESS: 'SIGN_OUT_SUCESS',
    SIGN_OUT_FALIURE: 'SIGN_OUT_FALIURE',
    SIGN_UP_START: 'SIGN_UP_START',
    SIGN_UP_SUCESS: 'SIGN_UP_SUCESS',
    SIGN_UP_FALIURE: 'SIGN_UP_FALIURE'
};

export default UserActionTypes;